import Head from "next/head";
import client from "../client";
import groq from "groq";

export async function getServerSideProps() {
  const query = groq`
  {
    "posts": *[_type == 'post']{...,
      'categories': categories[]->title,
      'authorName': author->name,
      'authorSlug': author-> slug,

    },
    "home": *[_type == 'homepage'],

    "navbar": *[_type == 'navbar'],

    "footer": *[_type == 'footer'],
    "contact": *[_type == 'contact'],
    "privatedocument": *[_type == 'privatedocument']{ 
        _id,
        title,
        "URL": document{asset->{path,url}}},
    "privatefolder": *[_type == 'privatefolder'] | order(title){
        ...,
        "relatedDocuments": *[_type=='privatedocument' && references(^._id)]{ _id,
          title,
          "URL": document{asset->{path,url} }
      },
    }
  }
  `;

  const data = await client.fetch(query);

  return {
    props: {
      posts: data.posts,
      home: data.home[0],
      footer: data.footer,
      navbar: data.navbar,
      contact: data.contact,
      privatedocument: data.privatedocument,
      privatefolder: data.privatefolder,
    },
  };
}

function Secret({ privatefolder, privatedocument }) {
  return (
    <div className="py-16 xl:py-36 px-4 sm:px-6 lg:px-8 bg-white overflow-hidden">
      <Head>
        <title>Secret Page | RM of Willowdale No. 153</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div>
        {privatefolder.map((item) => (
          <section className="text-gray-600 body-font" key={item.title}>
            <div className="container px-5 py-2 mx-auto">
              <div className="flex flex-col text-center w-full mb-0 ">
                <h1 className="sm:text-3xl text-2xl font-medium title-font mb-10 text-gray-900">
                  <div className="relative">
                    <div
                      className="absolute inset-0 flex items-center"
                      aria-hidden="true"
                    >
                      <div className="w-full border-t border-gray-300" />
                    </div>
                    <div className="relative flex justify-center">
                      <span className="px-3 bg-white text-xlg font-bold text-gray-900">
                        {item.title}
                      </span>
                    </div>
                  </div>
                </h1>
                <div className="pb-10">
                  <div className=" bg-white rounded-lg shadow">
                    <ul className="divide-y-2 divide-gray-100">
                      {item.relatedDocuments.map((step) => (
                        <a
                          href={step.URL.asset.url}
                          target="_blank"
                          rel="noreferrer"
                          key={step._id}
                        >
                          <li className="p-3">{step.title}</li>
                        </a>
                      ))}
                    </ul>
                  </div>
                </div>
              </div>
            </div>
          </section>
        ))}
      </div>
    </div>
  );
}

export default Secret;
